export default {
   allContent:{},
   datasget:{},
   clickShopid:1,
   allPrice:0,
   obj:[],
   arr1:[],
   arr2:'',
   arr3:{},
   zongjia:0,
   totalprice:0,
   shopID:0,
   getohasha:{},
   xiaobiaoId:'',
   jinweidu:{},
   // 心彦的部分
   loginac:"",
   userid:"",
   geohash:"",
   address:"",
   cityid:"",
   length:"0",
   datail:"",
   //记录是否登录
   dl:true,
   //长江修改的
   mingzi:{},
   latitude:{},
   longitude:{},
   xianshishenm:true,
   zxcc:{},
   cunchudizhi:[]
}